version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.100.0
    ports:
      - "4317:4317"
      - "55680:55680"
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml:z
    command: ["--config", "/etc/otel-collector-config.yaml"]

  tempo:
    image: grafana/tempo:2.7.0
    ports:
      - "3200:3200"
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo-config.yaml:z
    command: ["-config.file=/etc/tempo-config.yaml"]

  mimir:
    image: grafana/mimir:2.15.0
    ports:
      - "9009:9009"
    volumes:
      - ./config/mimir-config.yaml:/etc/mimir-config.yaml:z
    command: ["-config.file=/etc/mimir-config.yaml"]

  loki:
    image: grafana/loki:3.3.2
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki-config.yaml:z
    command: ["-config.file=/etc/loki-config.yaml"]

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./config/grafana-provisioning:/etc/grafana/provisioning:z