auth_enabled: false

server:
  http_listen_port: 3100

limits_config:
  allow_structured_metadata: true

common:
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  path_prefix: /tmp/loki

schema_config:
  configs:
    - store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks